// SPDX-License-Identifier: BSD-2-Clause
//! Manages sla specs and provides compiled slas.
//!
//! Provides the following:
//! - Source of truth for slaspec sources.
//! - Apply patches to specs.
//! - Compiled to sla and provided as const static byte slices
//! - Provides generated types for definitions (currently only user ops)
//!
//! ## Sla Specifications
//!
//! Sla specs are located in the `processors/` directory. The
//! `processors/ghidra/` directory is a copy of `Ghidra/Processors/` directory
//! in Ghidra sources. Processor definitions not sourced from Ghidra can be
//! placed under `processors/custom/`
//!
//! ## Patches
//!
//! Patches should be in unified format in the `patches/` folder. The directory
//! folder matches that of the `processors/` folder. The name of the patch file
//! should match the modified file name with the `.patch` extension added. The
//! names of modified files in the patch files are not read.
//!
//! Patches are created using [diffy](https://docs.rs/diffy/latest/diffy/).
//!
//! ### Patches from Github Pull Requests
//!
//! You can get PRs from GitHub in unified diff format by appending `.patch` or
//! `.diff` to the PR URL.
//!
//! For example:
//!
//! ```text
//! https://github.com/styx-emulator/styx-emulator/pull/353
//! https://github.com/styx-emulator/styx-emulator/pull/353.patch
//! https://github.com/styx-emulator/styx-emulator/pull/353.diff
//! ```
//!
//! ### Common Errors
//!
//! If you receive an `failed to apply patch: error applying hunk #n` for your
//! last hunk when building `styx-sla`, check to see if you have a trailing
//! newline. This is required if the final hunk in your patch is not the final
//! line in your patched file.
//!
use styx_cpu_type::arch::CpuRegister;
use styx_pcode::sla::{SlaSpec, SlaUserOps, UserOps};

use derive_more::{Display, FromStr};

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/sla_artifacts.rs"));

/// Defines conversion from [CpuRegister] to string for register lookup.
pub trait SlaRegisters {
    /// Return the symbol string in the sla spec corresponding to the given
    /// register. In the majority case this is a lower case conversion from the
    /// [CpuRegister::name()] but individual registers can be matched with
    /// custom names as well.
    fn translate_register(register: &CpuRegister) -> Box<str> {
        register.name().into()
    }
}

#[cfg(feature = "arch_aarch64")]
impl SlaRegisters for Aarch64 {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        // aarch64 sla has all lowercase register names
        register.name().to_lowercase().into_boxed_str()
    }
}

#[cfg(feature = "arch_arm")]
mod arm {
    use styx_cpu_type::arch::CpuRegister;

    /// common to all that use ARM.sinc where registers are defined
    fn translate_arm(register: &CpuRegister) -> Box<str> {
        // arm sla has all lowercase register names
        register.name().to_lowercase().into_boxed_str()
    }

    /// impl [`crate::SlaRegisters`] using [`translate_arm`]
    macro_rules! arm_sla_registers (
        ($p:ty) => {
            impl crate::SlaRegisters for $p {
                fn translate_register(register: &CpuRegister) -> Box<str> {
                    translate_arm(register)
                }
            }
        };
    );

    arm_sla_registers!(crate::Arm7Le);
    arm_sla_registers!(crate::Arm4Be);
    arm_sla_registers!(crate::Arm5Be);
    arm_sla_registers!(crate::Arm6Be);
    arm_sla_registers!(crate::Arm7Be);
    arm_sla_registers!(crate::Arm8Be);

    #[cfg(test)]
    mod tests {
        use crate::{Arm5BeUserOps, Arm7BeUserOps, Arm7LeUserOps};
        use core::str::FromStr;

        #[test]
        fn test_str() {
            assert_eq!(Arm7BeUserOps::Absolute.to_string(), "Absolute");
            assert_eq!(
                Arm7BeUserOps::from_str("Absolute").unwrap(),
                Arm7BeUserOps::Absolute
            );
            assert_eq!(
                Arm5BeUserOps::from_str(&Arm7LeUserOps::Absolute.to_string()).unwrap(),
                Arm5BeUserOps::Absolute
            );
        }
    }
}

#[cfg(feature = "arch_bfin")]
impl SlaRegisters for Blackfin {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        use styx_cpu_type::arch::{
            backends::{ArchRegister, BasicArchRegister},
            blackfin::BlackfinRegister,
        };

        let name = match register.variant() {
            ArchRegister::Basic(BasicArchRegister::Blackfin(BlackfinRegister::A0w)) => "A0.W",
            ArchRegister::Basic(BasicArchRegister::Blackfin(BlackfinRegister::A0x)) => "A0.X",
            ArchRegister::Basic(BasicArchRegister::Blackfin(BlackfinRegister::A1w)) => "A1.W",
            ArchRegister::Basic(BasicArchRegister::Blackfin(BlackfinRegister::A1x)) => "A1.X",
            _ => register.name(),
        };

        // blackfin sla has almost all uppercase register names, we need a special case for the ASTAT flag registers
        if name.contains("flag") {
            name.to_string().into_boxed_str()
        } else {
            name.to_uppercase().into_boxed_str()
        }
    }
}

#[cfg(feature = "arch_superh")]
impl SlaRegisters for SuperH4Be {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        let lower_name = register.name().to_lowercase();

        // some ghidra developer thought they'd be funny
        match lower_name.as_str() {
            "r0b" => "R0_BANK".into(),
            "r1b" => "R1_BANK".into(),
            "r2b" => "R2_BANK".into(),
            "r3b" => "R3_BANK".into(),
            "r4b" => "R4_BANK".into(),
            "r5b" => "R5_BANK".into(),
            "r6b" => "R6_BANK".into(),
            "r7b" => "R7_BANK".into(),
            "gbr" | "sr" | "ssr" | "spc" | "vbr" | "sgr" | "dbr" | "mach" | "macl" | "pr"
            | "pc" | "fpscr" | "fpul" => lower_name.to_uppercase().into_boxed_str(),
            _ => lower_name.into_boxed_str(),
        }
    }
}

#[cfg(feature = "arch_superh")]
impl SlaRegisters for SuperH4Le {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        let lower_name = register.name().to_lowercase();

        // some ghidra developer thought they'd be funny
        match lower_name.as_str() {
            "gbr" | "sr" | "ssr" | "spc" | "vbr" | "sgr" | "dbr" | "mach" | "macl" | "pr"
            | "pc" | "fpscr" | "fpul" => lower_name.to_uppercase().into_boxed_str(),
            _ => lower_name.into_boxed_str(),
        }
    }
}

#[cfg(feature = "arch_superh")]
impl SlaRegisters for Sh1 {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        // all lowercare registers
        register.name().to_lowercase().into_boxed_str()
    }
}

#[cfg(feature = "arch_superh")]
impl SlaRegisters for Sh2 {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        // all lowercare registers
        register.name().to_lowercase().into_boxed_str()
    }
}

#[cfg(feature = "arch_superh")]
impl SlaRegisters for Sh2a {
    fn translate_register(register: &CpuRegister) -> Box<str> {
        // all lowercare registers
        register.name().to_lowercase().into_boxed_str()
    }
}

#[cfg(feature = "arch_ppc")]
#[allow(unused_imports)] // wrong, this is a re-export
pub use ppc::*;
#[cfg(feature = "arch_ppc")]
mod ppc {
    //! PowerPC sla specifications
    //!
    //! Note: ppc_embedded.sinc may have mistakes.
    //!
    //! We've identified one mistake in the implementation of `mtmsr`
    //! instruction where the processor specification follows the "general
    //! processor" PowerISA instead of the embedded specification. If there are
    //! more differences we will construct an entirely new spec based on the
    //! Ghidra spec, instead of applying patches.

    use styx_cpu_type::arch::{
        backends::{ArchRegister, BasicArchRegister, SpecialArchRegister},
        ppc32::{Ppc32Register, SpecialPpc32Register, SprRegister},
        CpuRegister,
    };

    use crate::{Ppc324xxBe, SlaRegisters};

    impl SlaRegisters for Ppc324xxBe {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            let variant = register.variant();

            match variant {
                ArchRegister::Basic(BasicArchRegister::Ppc32(reg)) => ppc32_basic(register, reg),
                ArchRegister::Special(SpecialArchRegister::Ppc32(
                    SpecialPpc32Register::SprRegister(spr),
                )) => ppc32_special(spr),
                _ => "".to_owned().into_boxed_str(),
            }
        }
    }

    fn ppc32_special(spr: SprRegister) -> Box<str> {
        let spr_idx = spr.index();
        format!("spr{spr_idx:03x}").into_boxed_str()
    }

    fn ppc32_basic(register: &CpuRegister, reg: Ppc32Register) -> Box<str> {
        // note, there exists `crall` which you would think is Ppc32Register::CR,
        // however, ghidra represents `crall` as cr0-cr7 each taking a byte, when ppc
        // is actually cr0-cr7 each taking 4 bits. implemented in register handler instead 👍
        match reg {
            Ppc32Register::R0
            | Ppc32Register::R1
            | Ppc32Register::R2
            | Ppc32Register::R3
            | Ppc32Register::R4
            | Ppc32Register::R5
            | Ppc32Register::R6
            | Ppc32Register::R7
            | Ppc32Register::R8
            | Ppc32Register::R9
            | Ppc32Register::R10
            | Ppc32Register::R12
            | Ppc32Register::R13
            | Ppc32Register::R14
            | Ppc32Register::R15
            | Ppc32Register::R16
            | Ppc32Register::R17
            | Ppc32Register::R18
            | Ppc32Register::R19
            | Ppc32Register::R20
            | Ppc32Register::R21
            | Ppc32Register::R22
            | Ppc32Register::R23
            | Ppc32Register::R24
            | Ppc32Register::R25
            | Ppc32Register::R26
            | Ppc32Register::R27
            | Ppc32Register::R28
            | Ppc32Register::R29
            | Ppc32Register::R30
            | Ppc32Register::R31
            | Ppc32Register::Cr0
            | Ppc32Register::Cr1
            | Ppc32Register::Cr2
            | Ppc32Register::Cr3
            | Ppc32Register::Cr4
            | Ppc32Register::Cr5
            | Ppc32Register::Cr6
            | Ppc32Register::Cr7
            | Ppc32Register::Pc => register.name().to_lowercase(),
            Ppc32Register::TblR => "TBLr".to_owned(),
            Ppc32Register::TbuR => "TBUr".to_owned(),
            Ppc32Register::TblW => "TBLw".to_owned(),
            Ppc32Register::TbuW => "TBUw".to_owned(),
            _ => register.name().to_uppercase(),
        }
        .into_boxed_str()
    }
}

#[cfg(feature = "arch_m32r")]
#[allow(unused_imports)] // wrong, this is a re-export
pub use m32r::*;
#[cfg(feature = "arch_m32r")]
mod m32r {
    //! M32R sla specifications

    use styx_cpu_type::arch::CpuRegister;

    use crate::{M32r, SlaRegisters};

    impl SlaRegisters for M32r {
        fn translate_register(_register: &CpuRegister) -> Box<str> {
            unimplemented!()
        }
    }
}

#[cfg(any(feature = "arch_mips32", feature = "arch_mips64"))]
mod mips_common {
    use styx_cpu_type::arch::{
        backends::{ArchRegister, BasicArchRegister},
        mips32::Mips32Register,
        mips64::Mips64Register,
        CpuRegister,
    };

    pub(crate) fn translate_register(register: &CpuRegister) -> Box<str> {
        match register.variant() {
            // mips.sinc uses names from the O32 abi
            ArchRegister::Basic(BasicArchRegister::Mips32(reg)) => match reg {
                Mips32Register::R0 => "zero",
                Mips32Register::R1 => "at",
                Mips32Register::R2 => "v0",
                Mips32Register::R3 => "v1",
                Mips32Register::R4 => "a0",
                Mips32Register::R5 => "a1",
                Mips32Register::R6 => "a2",
                Mips32Register::R7 => "a3",
                Mips32Register::R8 => "t0",
                Mips32Register::R9 => "t1",
                Mips32Register::R10 => "t2",
                Mips32Register::R11 => "t3",
                Mips32Register::R12 => "t4",
                Mips32Register::R13 => "t5",
                Mips32Register::R14 => "t6",
                Mips32Register::R15 => "t7",
                Mips32Register::R16 => "s0",
                Mips32Register::R17 => "s1",
                Mips32Register::R18 => "s2",
                Mips32Register::R19 => "s3",
                Mips32Register::R20 => "s4",
                Mips32Register::R21 => "s5",
                Mips32Register::R22 => "s6",
                Mips32Register::R23 => "s7",
                Mips32Register::R24 => "t8",
                Mips32Register::R25 => "t9",
                Mips32Register::R26 => "k0",
                Mips32Register::R27 => "k1",
                Mips32Register::R28 => "gp",
                Mips32Register::R29 => "sp",
                Mips32Register::R30 => "s8",
                Mips32Register::R31 => "ra",
                _ => reg.register().name(),
            },
            ArchRegister::Basic(BasicArchRegister::Mips64(reg)) => match reg {
                Mips64Register::R0 => "zero",
                Mips64Register::R1 => "at",
                Mips64Register::R2 => "v0",
                Mips64Register::R3 => "v1",
                Mips64Register::R4 => "a0",
                Mips64Register::R5 => "a1",
                Mips64Register::R6 => "a2",
                Mips64Register::R7 => "a3",
                Mips64Register::R8 => "t0",
                Mips64Register::R9 => "t1",
                Mips64Register::R10 => "t2",
                Mips64Register::R11 => "t3",
                Mips64Register::R12 => "t4",
                Mips64Register::R13 => "t5",
                Mips64Register::R14 => "t6",
                Mips64Register::R15 => "t7",
                Mips64Register::R16 => "s0",
                Mips64Register::R17 => "s1",
                Mips64Register::R18 => "s2",
                Mips64Register::R19 => "s3",
                Mips64Register::R20 => "s4",
                Mips64Register::R21 => "s5",
                Mips64Register::R22 => "s6",
                Mips64Register::R23 => "s7",
                Mips64Register::R24 => "t8",
                Mips64Register::R25 => "t9",
                Mips64Register::R26 => "k0",
                Mips64Register::R27 => "k1",
                Mips64Register::R28 => "gp",
                Mips64Register::R29 => "sp",
                Mips64Register::R30 => "s8",
                Mips64Register::R31 => "ra",
                _ => reg.register().name(),
            },
            _ => "",
        }
        .to_lowercase()
        .into()
    }
}

#[cfg(feature = "arch_mips32")]
mod mips32 {
    //! mips32 sla specifications

    use super::*;

    impl SlaRegisters for Mips32be {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            crate::mips_common::translate_register(register)
        }
    }

    impl SlaRegisters for Mips32le {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            crate::mips_common::translate_register(register)
        }
    }
}

#[cfg(feature = "arch_mips64")]
mod mips64 {
    //! mips64 sla specifications

    use super::*;

    impl SlaRegisters for Mips64be {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            crate::mips_common::translate_register(register)
        }
    }

    impl SlaRegisters for Mips64le {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            crate::mips_common::translate_register(register)
        }
    }
}

#[cfg(feature = "arch_msp430")]
mod msp430 {
    //! msp430 sla specifications

    use styx_cpu_type::arch::CpuRegister;

    /// common register translations in TI430Common.sinc
    fn translate_msp430(register: &CpuRegister) -> Box<str> {
        register.name().to_uppercase().into_boxed_str()
    }

    impl crate::SlaRegisters for crate::TiMsp430x {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            translate_msp430(register)
        }
    }

    impl crate::SlaRegisters for crate::TiMsp430 {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            translate_msp430(register)
        }
    }
}

#[cfg(feature = "arch_hexagon")]
#[allow(unused_imports)] // wrong, this is a re-export
pub use hexagon::*;
#[cfg(feature = "arch_hexagon")]
mod hexagon {
    //! hexagon sla specifications

    use styx_cpu_type::arch::{
        backends::{ArchRegister, BasicArchRegister, GlobalArchRegister, SpecialArchRegister},
        hexagon::{GlobalHexagonRegister, HexagonRegister, SpecialHexagonRegister},
        CpuRegister,
    };

    impl crate::SlaRegisters for crate::Hexagon {
        fn translate_register(register: &CpuRegister) -> Box<str> {
            let variant = register.variant();

            hexagon_translate_register(&variant)
        }
    }

    pub fn hexagon_translate_register(register: &ArchRegister) -> Box<str> {
        match register {
            ArchRegister::Basic(BasicArchRegister::Hexagon(reg)) => hexagon_basic(reg),
            ArchRegister::Global(GlobalArchRegister::Hexagon(reg)) => hexagon_global(reg),
            ArchRegister::Special(SpecialArchRegister::Hexagon(reg)) => hexagon_special(reg),
            _ => "".to_owned().into_boxed_str(),
        }
    }

    pub fn hexagon_reg_to_str(hex_reg: &HexagonRegister) -> Box<str> {
        let default_name = &hex_reg.to_string();

        (match hex_reg {
            HexagonRegister::Sp => "R29",
            HexagonRegister::Fp => "R30",
            HexagonRegister::Lr => "R31",
            HexagonRegister::D0 => "R1R0",
            HexagonRegister::D1 => "R3R2",
            HexagonRegister::D2 => "R5R4",
            HexagonRegister::D3 => "R7R6",
            HexagonRegister::D4 => "R9R8",
            HexagonRegister::D5 => "R11R10",
            HexagonRegister::D6 => "R13R12",
            HexagonRegister::D7 => "R15R14",
            HexagonRegister::D8 => "R17R16",
            HexagonRegister::D9 => "R19R18",
            HexagonRegister::D10 => "R21R20",
            HexagonRegister::D11 => "R23R22",
            HexagonRegister::D12 => "R25R24",
            HexagonRegister::D13 => "R27R26",
            HexagonRegister::D14 => "R29R28",
            HexagonRegister::D15 => "R31R30",
            HexagonRegister::DestP0 => "D_P0",
            HexagonRegister::DestP1 => "D_P1",
            HexagonRegister::DestP2 => "D_P2",
            HexagonRegister::DestP3 => "D_P3",
            HexagonRegister::Sa0 => "C0",
            HexagonRegister::Lc0 => "C1",
            HexagonRegister::Sa1 => "C2",
            HexagonRegister::Lc1 => "C3",
            HexagonRegister::P3_0 => "C4",
            HexagonRegister::C5 => "C5",
            HexagonRegister::M0 => "C6",
            HexagonRegister::M1 => "C7",
            HexagonRegister::Usr => "C8",
            HexagonRegister::Pc => "C9",
            HexagonRegister::Ugp => "C10",
            HexagonRegister::Gp => "C11",
            HexagonRegister::Cs0 => "C12",
            HexagonRegister::Cs1 => "C13",
            HexagonRegister::UpcycleLo => "C14",
            HexagonRegister::UpcycleHi => "C15",
            HexagonRegister::FrameLimit => "C16",
            HexagonRegister::FrameKey => "C17",
            HexagonRegister::PktCountLo => "C18",
            HexagonRegister::PktCountHi => "C19",
            HexagonRegister::EmuPktCount => "C20", // C20, From QEMU definitions: hex_regs.h and cpu.c's hexagon_regnmaes
            HexagonRegister::EmuInsnCount => "C21", // C21, From QEMU: see above
            HexagonRegister::EmuHvxCount => "C22", // C22, From QEMU: see above
            HexagonRegister::UtimerLo => "C30",
            HexagonRegister::UtimerHi => "C31",
            HexagonRegister::Cs => "C13C12",
            HexagonRegister::Upcycle => "C15C14",
            HexagonRegister::C17C16 => "C17C16",
            HexagonRegister::PktCount => "C19C18",
            HexagonRegister::Utimer => "C31C30",
            // For some reason, the slaspec defines S0
            // and S1, but never uses them in any instruction.
            // TODO: patch the slaspec
            HexagonRegister::Sgp0 => "SGP0",
            HexagonRegister::Sgp1 => "SGP1",
            HexagonRegister::Stid => "S2",
            HexagonRegister::Elr => "S3",
            HexagonRegister::BadVa0 => "S4",
            HexagonRegister::BadVa1 => "S5",
            HexagonRegister::Ssr => "S6",
            HexagonRegister::Ccr => "S7",
            HexagonRegister::Htid => "S8",
            // HexagonRegister::BadVa => "S9",
            HexagonRegister::Imask => "S10",
            HexagonRegister::Gevb => "S11",
            HexagonRegister::VwCtrl => "S12",
            HexagonRegister::S13 => "S13",
            HexagonRegister::S14 => "S14",
            HexagonRegister::S15 => "S15",
            HexagonRegister::SGP1SGP0 => "SGP1SGP0",
            HexagonRegister::S3S2
            | HexagonRegister::S5S4
            | HexagonRegister::S7S6
            | HexagonRegister::S9S8
            | HexagonRegister::S11S10
            | HexagonRegister::S13S12
            | HexagonRegister::S15S14 => default_name,
            HexagonRegister::Gelr => "G0",
            HexagonRegister::Gsr => "G1",
            HexagonRegister::Gosp => "G2",
            HexagonRegister::GbadVa => "G3",
            HexagonRegister::Gcommit1t => "G4",
            HexagonRegister::Gcommit2t => "G5",
            HexagonRegister::Gcommit3t => "G6",
            HexagonRegister::Gcommit4t => "G7",
            HexagonRegister::Gcommit5t => "G8",
            HexagonRegister::Gcommit6t => "G9",
            HexagonRegister::Gpcycle1t => "G10",
            HexagonRegister::Gpcycle2t => "G11",
            HexagonRegister::Gpcycle3t => "G12",
            HexagonRegister::Gpcycle4t => "G13",
            HexagonRegister::Gpcycle5t => "G14",
            HexagonRegister::Gpcycle6t => "G15",
            HexagonRegister::Gpmucnt4 => "G16",
            HexagonRegister::Gpmucnt5 => "G17",
            HexagonRegister::Gpmucnt6 => "G18",
            HexagonRegister::Gpmucnt7 => "G19",
            HexagonRegister::Gcommit7t => "G20",
            HexagonRegister::Gcommit8t => "G21",
            HexagonRegister::Gpcycle7t => "G22",
            HexagonRegister::Gpcycle8t => "G23",
            HexagonRegister::Gpcyclelo => "G24",
            HexagonRegister::Gpcyclehi => "G25",
            HexagonRegister::Gpmucnt0 => "G26",
            HexagonRegister::Gpmucnt1 => "G27",
            HexagonRegister::Gpmucnt2 => "G28",
            HexagonRegister::Gpmucnt3 => "G29",
            HexagonRegister::G30 | HexagonRegister::G31 => default_name,
            HexagonRegister::G1G0
            | HexagonRegister::G3G2
            | HexagonRegister::G5G4
            | HexagonRegister::G7G6
            | HexagonRegister::G9G8
            | HexagonRegister::G11G10
            | HexagonRegister::G13G12
            | HexagonRegister::G15G14
            | HexagonRegister::G17G16
            | HexagonRegister::G19G18
            | HexagonRegister::G21G20
            | HexagonRegister::G23G22
            | HexagonRegister::G25G24
            | HexagonRegister::G27G26
            | HexagonRegister::G29G28
            | HexagonRegister::G31G30 => default_name,
            _ => default_name,
        })
        .to_owned()
        .into_boxed_str()
    }

    pub fn hexagon_global_reg_to_str(hex_reg: &GlobalHexagonRegister) -> Box<str> {
        let default_name = &hex_reg.to_string();

        (match hex_reg {
            GlobalHexagonRegister::Evb => "S16",
            GlobalHexagonRegister::ModeCtl => "S17",
            GlobalHexagonRegister::SysCfg => "S18",
            GlobalHexagonRegister::Segment => "S19",
            GlobalHexagonRegister::Ipendad => "S20",
            GlobalHexagonRegister::Vid => "S21",
            GlobalHexagonRegister::Vid1 => "S22",
            GlobalHexagonRegister::BestWait => "S23",
            GlobalHexagonRegister::S24 => "S24",
            GlobalHexagonRegister::SchedCfg => "S25",
            GlobalHexagonRegister::S26 => "S26",
            GlobalHexagonRegister::CfgBase => "S27",
            GlobalHexagonRegister::Diag => "S28",
            GlobalHexagonRegister::Rev => "S29",
            GlobalHexagonRegister::PcycleLo => "S30",
            GlobalHexagonRegister::PcycleHi => "S31",
            GlobalHexagonRegister::IsdbSt => "S32",
            GlobalHexagonRegister::IsdbCfg0 => "S33",
            GlobalHexagonRegister::IsdbCfg1 => "S34",
            GlobalHexagonRegister::Livelock => "S35",
            GlobalHexagonRegister::BrkptPc0 => "S36",
            GlobalHexagonRegister::BrkptCfg0 => "S37",
            GlobalHexagonRegister::BrkptPc1 => "S38",
            GlobalHexagonRegister::BrkptCfg1 => "S39",
            GlobalHexagonRegister::IsdbMbxIn => "S40",
            GlobalHexagonRegister::IsdbMbxOut => "S41",
            GlobalHexagonRegister::IsdbEn => "S42",
            GlobalHexagonRegister::IsdbGpr => "S43",
            GlobalHexagonRegister::PmuCnt4 => "S44",
            GlobalHexagonRegister::PmuCnt5 => "S45",
            GlobalHexagonRegister::PmuCnt6 => "S46",
            GlobalHexagonRegister::PmuCnt7 => "S47",
            GlobalHexagonRegister::PmuCnt0 => "S48",
            GlobalHexagonRegister::PmuCnt1 => "S49",
            GlobalHexagonRegister::PmuCnt2 => "S50",
            GlobalHexagonRegister::PmuCnt3 => "S51",
            GlobalHexagonRegister::PmuEvtCfg => "S52",
            GlobalHexagonRegister::PmuStId0 => "S53",
            GlobalHexagonRegister::PmuEvtCfg1 => "S54",
            GlobalHexagonRegister::PmuStId1 => "S55",
            GlobalHexagonRegister::TimerLo => "S56",
            GlobalHexagonRegister::TimerHi => "S57",
            GlobalHexagonRegister::PmuCfg => "S58",
            GlobalHexagonRegister::Rgdr2 => "S59",
            GlobalHexagonRegister::Rgdr => "S60",
            GlobalHexagonRegister::Turkey => "S61",
            GlobalHexagonRegister::Duck => "S62",
            GlobalHexagonRegister::Chicken => "S63",
            GlobalHexagonRegister::Commit1t => "S64",
            GlobalHexagonRegister::Commit2t => "S65",
            GlobalHexagonRegister::Commit3t => "S66",
            GlobalHexagonRegister::Commit4t => "S67",
            GlobalHexagonRegister::Commit5t => "S68",
            GlobalHexagonRegister::Commit6t => "S69",
            GlobalHexagonRegister::Pcycle1t => "S70",
            GlobalHexagonRegister::Pcycle2t => "S71",
            GlobalHexagonRegister::Pcycle3t => "S72",
            GlobalHexagonRegister::Pcycle4t => "S73",
            GlobalHexagonRegister::Pcycle5t => "S74",
            GlobalHexagonRegister::Pcycle6t => "S75",
            GlobalHexagonRegister::StfInst => "S76",
            GlobalHexagonRegister::IsdbCmd => "S77",
            GlobalHexagonRegister::IsdbVer => "S78",
            GlobalHexagonRegister::BrkptInfo => "S79",
            GlobalHexagonRegister::Rgdr3 => "S80",
            GlobalHexagonRegister::Commit7t => "S81",
            GlobalHexagonRegister::Commit8t => "S82",
            GlobalHexagonRegister::Pcycle7t => "S83",
            GlobalHexagonRegister::Pcycle8t => "S84",
            GlobalHexagonRegister::Commit9t => "S85",
            GlobalHexagonRegister::Commit10t => "S86",
            GlobalHexagonRegister::Commit11t => "S87",
            GlobalHexagonRegister::Commit12t => "S88",
            GlobalHexagonRegister::Commit13t => "S89",
            GlobalHexagonRegister::Commit14t => "S90",
            GlobalHexagonRegister::Commit15t => "S91",
            GlobalHexagonRegister::Commit16t => "S92",
            GlobalHexagonRegister::Pcycle9t => "S93",
            GlobalHexagonRegister::Pcycle10t => "S94",
            GlobalHexagonRegister::Pcycle11t => "S95",
            GlobalHexagonRegister::Pcycle12t => "S96",
            GlobalHexagonRegister::Pcycle13t => "S97",
            GlobalHexagonRegister::Pcycle14t => "S98",
            GlobalHexagonRegister::Pcycle15t => "S99",
            GlobalHexagonRegister::Pcycle16t => "S100",
            GlobalHexagonRegister::Ipend => "S101",
            GlobalHexagonRegister::Iad => "S102",
            GlobalHexagonRegister::IsdbSt1 => "S103",
            GlobalHexagonRegister::IsdbSt2 => "S104",
            GlobalHexagonRegister::BrkptInfo1 => "S105",
            GlobalHexagonRegister::Timer => "S57S56",
            GlobalHexagonRegister::Pcycle => "S31S30",
            GlobalHexagonRegister::S17S16
            | GlobalHexagonRegister::S19S18
            | GlobalHexagonRegister::S21S20
            | GlobalHexagonRegister::S23S22
            | GlobalHexagonRegister::S25S24
            | GlobalHexagonRegister::S27S26
            | GlobalHexagonRegister::S29S28
            | GlobalHexagonRegister::S33S32
            | GlobalHexagonRegister::S35S34
            | GlobalHexagonRegister::S37S36
            | GlobalHexagonRegister::S39S38
            | GlobalHexagonRegister::S41S40
            | GlobalHexagonRegister::S43S42
            | GlobalHexagonRegister::S45S44
            | GlobalHexagonRegister::S47S46
            | GlobalHexagonRegister::S49S48
            | GlobalHexagonRegister::S51S50
            | GlobalHexagonRegister::S53S52
            | GlobalHexagonRegister::S55S54
            | GlobalHexagonRegister::S59S58
            | GlobalHexagonRegister::S61S60
            | GlobalHexagonRegister::S63S62
            | GlobalHexagonRegister::S65S64
            | GlobalHexagonRegister::S67S66
            | GlobalHexagonRegister::S69S68
            | GlobalHexagonRegister::S71S70
            | GlobalHexagonRegister::S73S72
            | GlobalHexagonRegister::S75S74
            | GlobalHexagonRegister::S77S76
            | GlobalHexagonRegister::S79S78 => default_name,
        })
        .to_owned()
        .into_boxed_str()
    }

    pub fn hexagon_special_reg_to_str(hex_reg: &SpecialHexagonRegister) -> Box<str> {
        let default_name = &hex_reg.to_string();

        (match hex_reg {
            SpecialHexagonRegister::BadVaRegister(_) => "S9",
        })
        .to_owned()
        .into_boxed_str()
    }

    fn hexagon_special(hex_reg: &SpecialHexagonRegister) -> Box<str> {
        hexagon_special_reg_to_str(hex_reg)
    }

    fn hexagon_global(hex_reg: &GlobalHexagonRegister) -> Box<str> {
        hexagon_global_reg_to_str(hex_reg)
    }

    fn hexagon_basic(hex_reg: &HexagonRegister) -> Box<str> {
        // The slaspec doesn't have support for the
        // vector registers at the moment.
        // TODO: Things could get very messy if we update a register name and
        // currently the register is covered in the match fallthrough arm.
        //
        // Eg. if C24 gets named something else in the HexagonRegister struct (defined
        // in macro), then this match will not handle that.
        // I have explicitly redefined all the system and guest registers here for this reason,
        // as in the future we may have names for them, and it would be good for rust to throw an error
        // or have to explicitly modify this match if/when that rename happens.

        hexagon_reg_to_str(hex_reg)
    }
}

#[cfg(test)]
#[cfg(feature = "arch_arm")]
mod tests {
    use super::*;

    #[test]
    fn test_arm() {
        let name = Arm7Le::name();
        assert_eq!(name, "ARM7_le");
        assert!(!Arm7Le::spec().is_empty());

        assert_eq!(Arm7LeUserOps::JazelleBranch.index(), 41);
    }

    #[test]
    fn test_patch() {
        assert_eq!(Arm7LeUserOps::TestPatch.index(), 62);
    }
}
