use crate::arch_spec::hexagon::tests::*;
use log::info;
use styx_processor::{
    cpu::CpuBackendExt,
    hooks::{CoreHandle, Hookable},
};
use test_case::test_case;

use super::setup_objdump;

/// TODO: instructions that do both loads and stores!
/// Such as { 	memb(r0+#0x18) |= r3 }
fn wrong_size_sext_wrapper(
    objdump: &str,
    r21: u32,
    r22: u32,
    r23: u32,
    r24: u32,
    num_packets: u64,
    data_size: u32,
    is_load_test: bool,
) {
    const MEM_RANGE_MIN: u64 = 0x0;
    const MEM_RANGE_MAX: u64 = 0x500;
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    // R0 and R2 are used as memory address "bases"
    cpu.write_register(HexagonRegister::R0, MEM_RANGE_MIN as u32)
        .unwrap();
    cpu.write_register(HexagonRegister::R2, MEM_RANGE_MIN as u32 + 0x100)
        .unwrap();
    // R1 and R3 are not used as a "base" in an address but rather
    // used to compute an offset
    cpu.write_register(HexagonRegister::R3, 0x4u32).unwrap();
    cpu.write_register(HexagonRegister::R1, 0x8u32).unwrap();

    cpu.write_register(HexagonRegister::R21, r21).unwrap();
    cpu.write_register(HexagonRegister::R22, r22).unwrap();
    cpu.write_register(HexagonRegister::R23, r23).unwrap();
    cpu.write_register(HexagonRegister::R24, r24).unwrap();

    cpu.add_hook(styx_processor::hooks::StyxHook::MemoryWrite(
        (0..(u32::MAX as u64)).into(),
        Box::new(
            move |mut proc: CoreHandle, address: u64, size: u32, data: &[u8]| {
                info!("address {address:x} size {size}");
                assert!(size == data_size);
                Ok(())
            },
        ),
    ))
    .unwrap();

    cpu.add_hook(styx_processor::hooks::StyxHook::MemoryRead(
        (0..(u32::MAX as u64)).into(),
        Box::new(
            move |mut proc: CoreHandle, address: u64, size: u32, data: &mut [u8]| {
                assert!(address >= MEM_RANGE_MIN && address <= MEM_RANGE_MAX);
                assert!(size == data_size);

                // Since these reads should sign extend, we should make sure that -1 is returned.
                // A 2 byte read reads 0x0000 but we give it 0xffff. Then on extension, we get
                // 0xffffffff.
                for byt in &mut *data {
                    *byt = 0xff;
                }

                info!("address {address:x} size {size} data {data:x?}");
                Ok(())
            },
        ),
    ))
    .unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, num_packets).unwrap();

    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    // R1 is always the register being written, and thus the reigster that we have to care about.
    if is_load_test {
        let r1 = cpu.read_register::<u32>(HexagonRegister::R1).unwrap();
        // Test the sign extension
        assert_eq!(r1, 0xffffffff)
    }
}

/// Some store instructions are supposed to store 1 byte or
/// 2 bytes, but they store 4 bytes, overwriting other parts of memory
/// insidiously.
///
/// These test cases are autogenerated from a list of suspicious instructions
/// that seem to do this sort of behaviour.
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	01 cb 00 41	4100cb01 { 	if (p1) r1 = memb(r0+#0x18) }
	"#, 1, 2, 11029, 11029, 2, 1; "L2_ploadrbt_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 e3 02 9b	9b02e381 { 	if (p1) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 2, 1; "L2_ploadrbt_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	01 cb 00 45	4500cb01 { 	if (!p1) r1 = memb(r0+#0x18) }
	"#, 1, 2, 3, 4, 2, 1; "L2_ploadrbf_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 eb 02 9b	9b02eb81 { 	if (!p1) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 3, 4, 2, 1; "L2_ploadrbf_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	01 cb 00 43	4300cb01   	if (p1.new) r1 = memb(r0+#0x18) }
	"#, 1, 2, 11029, 11029, 1, 1; "L2_ploadrbtnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	01 cb 00 47	4700cb01   	if (!p1.new) r1 = memb(r0+#0x18) }
	"#, 1, 2, 3, 4, 1, 1; "L2_ploadrbfnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 00 30	3000c381 { 	if (p0) r1 = memb(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 2, 1; "L4_ploadrbt_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 00 31	3100c381 { 	if (!p0) r1 = memb(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 2, 1; "L4_ploadrbf_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 00 32	3200c381   	if (p0.new) r1 = memb(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 1, 1; "L4_ploadrbtnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 00 33	3300c381   	if (!p0.new) r1 = memb(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 1, 1; "L4_ploadrbfnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 f3 02 9b	9b02f381   	if (p1.new) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 1, 1; "L2_ploadrbtnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 fb 02 9b	9b02fb81   	if (!p1.new) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 3, 4, 1, 1; "L2_ploadrbfnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 e2 00 9f	9f00e281   	if (p1) r1 = memb(##0x0) }
	"#, 1, 2, 11029, 11029, 2, 1; "L4_ploadrbt_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 ea 00 9f	9f00ea81   	if (!p1) r1 = memb(##0x0) }
	"#, 1, 2, 3, 4, 2, 1; "L4_ploadrbf_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 f2 00 9f	9f00f281   	if (p1.new) r1 = memb(##0x0) }
	"#, 1, 2, 11029, 11029, 1, 1; "L4_ploadrbtnew_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 fa 00 9f	9f00fa81   	if (!p1.new) r1 = memb(##0x0) }
	"#, 1, 2, 3, 4, 1, 1; "L4_ploadrbfnew_abs"
)]
#[test_case(
	r#"
0:	01 cf 00 49	4900cf01 { 	r1 = memb(gp+#0x78) }
	"#, 1, 2, 3, 4, 1, 1; "L2_loadrbgp"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 cf 40 41	4140cf81 { 	if (p1) r1 = memh(r0+#0x78) }
	"#, 1, 2, 11029, 11029, 2, 2; "L2_ploadrht_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	c1 e3 42 9b	9b42e3c1 { 	if (p1) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 2, 2; "L2_ploadrht_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 cf 40 45	4540cf81 { 	if (!p1) r1 = memh(r0+#0x78) }
	"#, 1, 2, 3, 4, 2, 2; "L2_ploadrhf_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	c1 eb 42 9b	9b42ebc1 { 	if (!p1) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 3, 4, 2, 2; "L2_ploadrhf_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 cf 40 43	4340cf81   	if (p1.new) r1 = memh(r0+#0x78) }
	"#, 1, 2, 11029, 11029, 1, 2; "L2_ploadrhtnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 cf 40 47	4740cf81   	if (!p1.new) r1 = memh(r0+#0x78) }
	"#, 1, 2, 3, 4, 1, 2; "L2_ploadrhfnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 40 30	3040c381 { 	if (p0) r1 = memh(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 2, 2; "L4_ploadrht_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 40 31	3140c381 { 	if (!p0) r1 = memh(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 2, 2; "L4_ploadrhf_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 40 32	3240c381   	if (p0.new) r1 = memh(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 1, 2; "L4_ploadrhtnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 40 33	3340c381   	if (!p0.new) r1 = memh(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 1, 2; "L4_ploadrhfnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	c1 f3 42 9b	9b42f3c1   	if (p1.new) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 1, 2; "L2_ploadrhtnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	c1 fb 42 9b	9b42fbc1   	if (!p1.new) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 3, 4, 1, 2; "L2_ploadrhfnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 e2 40 9f	9f40e281   	if (p1) r1 = memh(##0x0) }
	"#, 1, 2, 11029, 11029, 2, 2; "L4_ploadrht_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 ea 40 9f	9f40ea81   	if (!p1) r1 = memh(##0x0) }
	"#, 1, 2, 3, 4, 2, 2; "L4_ploadrhf_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 f2 40 9f	9f40f281   	if (p1.new) r1 = memh(##0x0) }
	"#, 1, 2, 11029, 11029, 1, 2; "L4_ploadrhtnew_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 fa 40 9f	9f40fa81   	if (!p1.new) r1 = memh(##0x0) }
	"#, 1, 2, 3, 4, 1, 2; "L4_ploadrhfnew_abs"
)]
#[test_case(
	r#"
0:	81 c7 40 49	4940c781 { 	r1 = memh(gp+#0x78) }
	"#, 1, 2, 3, 4, 1, 2; "L2_loadrhgp"
)]
fn wrong_sext_loads(
    objdump: &str,
    r21: u32,
    r22: u32,
    r23: u32,
    r24: u32,
    num_packets: u64,
    data_size: u32,
) {
    wrong_size_sext_wrapper(objdump, r21, r22, r23, r24, num_packets, data_size, true)
}
