use crate::arch_spec::hexagon::tests::*;
use log::info;
use styx_processor::{
    cpu::CpuBackendExt,
    hooks::{CoreHandle, Hookable},
};
use test_case::test_case;

use super::setup_objdump;

/// TODO: instructions that do both loads and stores!
/// Such as { 	memb(r0+#0x18) |= r3 }
fn wrong_size_sext_wrapper(
    objdump: &str,
    r21: u32,
    r22: u32,
    r23: u32,
    r24: u32,
    num_packets: u64,
    data_size: u32,
    is_load_test: bool,
) {
    const MEM_RANGE_MIN: u64 = 0x0;
    const MEM_RANGE_MAX: u64 = 0x500;
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    // R0 and R2 are used as memory address "bases"
    cpu.write_register(HexagonRegister::R0, MEM_RANGE_MIN as u32)
        .unwrap();
    cpu.write_register(HexagonRegister::R2, MEM_RANGE_MIN as u32 + 0x100)
        .unwrap();
    // R1 and R3 are not used as a "base" in an address but rather
    // used to compute an offset
    cpu.write_register(HexagonRegister::R3, 0x4u32).unwrap();
    cpu.write_register(HexagonRegister::R1, 0x8u32).unwrap();

    cpu.write_register(HexagonRegister::R21, r21).unwrap();
    cpu.write_register(HexagonRegister::R22, r22).unwrap();
    cpu.write_register(HexagonRegister::R23, r23).unwrap();
    cpu.write_register(HexagonRegister::R24, r24).unwrap();

    cpu.add_hook(styx_processor::hooks::StyxHook::MemoryWrite(
        (0..(u32::MAX as u64)).into(),
        Box::new(
            move |mut proc: CoreHandle, address: u64, size: u32, data: &[u8]| {
                info!("address {address:x} size {size}");
                assert!(size == data_size);
                Ok(())
            },
        ),
    ))
    .unwrap();

    cpu.add_hook(styx_processor::hooks::StyxHook::MemoryRead(
        (0..(u32::MAX as u64)).into(),
        Box::new(
            move |mut proc: CoreHandle, address: u64, size: u32, data: &mut [u8]| {
                assert!(address >= MEM_RANGE_MIN && address <= MEM_RANGE_MAX);
                assert!(size == data_size);

                // Since these reads should sign extend, we should make sure that -1 is returned.
                // A 2 byte read reads 0x0000 but we give it 0xffff. Then on extension, we get
                // 0xffffffff.
                for byt in &mut *data {
                    *byt = 0xff;
                }

                info!("address {address:x} size {size} data {data:x?}");
                Ok(())
            },
        ),
    ))
    .unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, num_packets).unwrap();

    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    // R1 is always the register being written, and thus the reigster that we have to care about.
    if is_load_test {
        let r1 = cpu.read_register::<u32>(HexagonRegister::R1).unwrap();
        // Test the sign extension
        assert_eq!(r1, 0xffffffff)
    }
}

/// Some store instructions are supposed to store 1 byte or
/// 2 bytes, but they store 4 bytes, overwriting other parts of memory
/// insidiously.
///
/// These test cases are autogenerated from a list of suspicious instructions
/// that seem to do this sort of behaviour.
#[test_case(
	r#"
       0:	03 cc 00 3e	3e00cc03 { 	memb(r0+#0x18) += r3 } 
	"#, 1, 2, 3, 4, 1, 1; "L4_add_memopb_io"
)]
#[test_case(
	r#"
       0:	23 cc 00 3e	3e00cc23 { 	memb(r0+#0x18) -= r3 } 
	"#, 1, 2, 3, 4, 1, 1; "L4_sub_memopb_io"
)]
#[test_case(
	r#"
       0:	43 cc 00 3e	3e00cc43 { 	memb(r0+#0x18) &= r3 } 
	"#, 1, 2, 3, 4, 1, 1; "L4_and_memopb_io"
)]
#[test_case(
	r#"
       0:	63 cc 00 3e	3e00cc63 { 	memb(r0+#0x18) |= r3 } 
	"#, 1, 2, 3, 4, 1, 1; "L4_or_memopb_io"
)]
#[test_case(
	r#"
       0:	0c cc 00 3f	3f00cc0c { 	memb(r0+#0x18) += #0xc } 
	"#, 1, 2, 3, 4, 1, 1; "L4_iadd_memopb_io"
)]
#[test_case(
	r#"
       0:	2c cc 00 3f	3f00cc2c { 	memb(r0+#0x18) -= #0xc } 
	"#, 1, 2, 3, 4, 1, 1; "L4_isub_memopb_io"
)]
#[test_case(
	r#"
       0:	4c cc 00 3f	3f00cc4c { 	memb(r0+#0x18) = clrbit(#0xc) } 
	"#, 1, 2, 3, 4, 1, 1; "L4_iand_memopb_io"
)]
#[test_case(
	r#"
       0:	6c cc 00 3f	3f00cc6c { 	memb(r0+#0x18) = setbit(#0xc) } 
	"#, 1, 2, 3, 4, 1, 1; "L4_ior_memopb_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	1e ec 00 38	3800ec1e { 	if (p0) memb(r0+#0x18) = #-0x2 } 
	"#, 99, 99, 3, 4, 2, 1; "S4_storeirbt_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	1e ec 80 38	3880ec1e { 	if (!p0) memb(r0+#0x18) = #-0x2 } 
	"#, 1, 2, 3, 4, 2, 1; "S4_storeirbf_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	1e ec 00 39	3900ec1e   	if (p0.new) memb(r0+#0x18) = #-0x2 } 
	"#, 99, 99, 3, 4, 1, 1; "S4_storeirbtnew_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	1e ec 80 39	3980ec1e   	if (!p0.new) memb(r0+#0x18) = #-0x2 } 
	"#, 1, 2, 3, 4, 1, 1; "S4_storeirbfnew_io"
)]
#[test_case(
	r#"
       0:	7d ec 00 3c	3c00ec7d { 	memb(r0+#0x18) = #-0x3 } 
	"#, 1, 2, 3, 4, 1, 1; "S4_storeirb_io"
)]
#[test_case(
	r#"
       0:	03 de 20 3e	3e20de03 { 	memh(r0+#0x78) += r3 } 
	"#, 1, 2, 3, 4, 1, 2; "L4_add_memoph_io"
)]
#[test_case(
	r#"
       0:	23 de 20 3e	3e20de23 { 	memh(r0+#0x78) -= r3 } 
	"#, 1, 2, 3, 4, 1, 2; "L4_sub_memoph_io"
)]
#[test_case(
	r#"
       0:	43 de 20 3e	3e20de43 { 	memh(r0+#0x78) &= r3 } 
	"#, 1, 2, 3, 4, 1, 2; "L4_and_memoph_io"
)]
#[test_case(
	r#"
       0:	63 de 20 3e	3e20de63 { 	memh(r0+#0x78) |= r3 } 
	"#, 1, 2, 3, 4, 1, 2; "L4_or_memoph_io"
)]
#[test_case(
	r#"
       0:	0c de 20 3f	3f20de0c { 	memh(r0+#0x78) += #0xc } 
	"#, 1, 2, 3, 4, 1, 2; "L4_iadd_memoph_io"
)]
#[test_case(
	r#"
       0:	2c de 20 3f	3f20de2c { 	memh(r0+#0x78) -= #0xc } 
	"#, 1, 2, 3, 4, 1, 2; "L4_isub_memoph_io"
)]
#[test_case(
	r#"
       0:	4c de 20 3f	3f20de4c { 	memh(r0+#0x78) = clrbit(#0xc) } 
	"#, 1, 2, 3, 4, 1, 2; "L4_iand_memoph_io"
)]
#[test_case(
	r#"
       0:	6c de 20 3f	3f20de6c { 	memh(r0+#0x78) = setbit(#0xc) } 
	"#, 1, 2, 3, 4, 1, 2; "L4_ior_memoph_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	1e fe 20 38	3820fe1e { 	if (p0) memh(r0+#0x78) = #-0x2 } 
	"#, 99, 99, 3, 4, 2, 2; "S4_storeirht_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	1e fe a0 38	38a0fe1e { 	if (!p0) memh(r0+#0x78) = #-0x2 } 
	"#, 1, 2, 3, 4, 2, 2; "S4_storeirhf_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	1e fe 20 39	3920fe1e   	if (p0.new) memh(r0+#0x78) = #-0x2 } 
	"#, 99, 99, 3, 4, 1, 2; "S4_storeirhtnew_io"
)]
#[test_case(
	r#"
       0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	1e fe a0 39	39a0fe1e   	if (!p0.new) memh(r0+#0x78) = #-0x2 } 
	"#, 1, 2, 3, 4, 1, 2; "S4_storeirhfnew_io"
)]
#[test_case(
	r#"
       0:	7d fe 20 3c	3c20fe7d { 	memh(r0+#0x78) = #-0x3 } 
	"#, 1, 2, 3, 4, 1, 2; "S4_storeirh_io"
)]
// Duplexes, which I did by hand since I can't be bothered to add the logic
// to my test generator
#[test_case(
    r#"
       0:	00 40 00 7f	7f004000 { 	nop
       4:	00 40 00 7f	7f004000   	nop
       8:	02 32 0e 7a	7a0e3202   	r22 = #-0x1; 	memb(r0+#0x2) = #0 } 
    "#, 1, 2, 3, 4, 1, 1; "SS2_storebi0"
)]
#[test_case(
    r#"
       0:	00 40 00 7f	7f004000 { 	nop
       4:	00 40 00 7f	7f004000   	nop
       8:	02 33 0e 7a	7a0e3302   	r22 = #-0x1; 	memb(r0+#0x2) = #1 } 
    "#, 1, 2, 3, 4, 1, 1; "SS2_storebi1"
)]
fn wrong_size_stores(
    objdump: &str,
    r21: u32,
    r22: u32,
    r23: u32,
    r24: u32,
    num_packets: u64,
    data_size: u32,
) {
    wrong_size_sext_wrapper(objdump, r21, r22, r23, r24, num_packets, data_size, false)
}

// Separate functions are exclusively for readability
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	01 cb 00 41	4100cb01 { 	if (p1) r1 = memb(r0+#0x18) }
	"#, 1, 2, 11029, 11029, 2, 1; "L2_ploadrbt_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 e3 02 9b	9b02e381 { 	if (p1) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 2, 1; "L2_ploadrbt_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	01 cb 00 45	4500cb01 { 	if (!p1) r1 = memb(r0+#0x18) }
	"#, 1, 2, 3, 4, 2, 1; "L2_ploadrbf_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 eb 02 9b	9b02eb81 { 	if (!p1) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 3, 4, 2, 1; "L2_ploadrbf_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	01 cb 00 43	4300cb01   	if (p1.new) r1 = memb(r0+#0x18) }
	"#, 1, 2, 11029, 11029, 1, 1; "L2_ploadrbtnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	01 cb 00 47	4700cb01   	if (!p1.new) r1 = memb(r0+#0x18) }
	"#, 1, 2, 3, 4, 1, 1; "L2_ploadrbfnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 00 30	3000c381 { 	if (p0) r1 = memb(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 2, 1; "L4_ploadrbt_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 00 31	3100c381 { 	if (!p0) r1 = memb(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 2, 1; "L4_ploadrbf_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 00 32	3200c381   	if (p0.new) r1 = memb(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 1, 1; "L4_ploadrbtnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 00 33	3300c381   	if (!p0.new) r1 = memb(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 1, 1; "L4_ploadrbfnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 f3 02 9b	9b02f381   	if (p1.new) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 1, 1; "L2_ploadrbtnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 fb 02 9b	9b02fb81   	if (!p1.new) r1 = memb(r2++#-0x4) }
	"#, 1, 2, 3, 4, 1, 1; "L2_ploadrbfnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 e2 00 9f	9f00e281   	if (p1) r1 = memb(##0x0) }
	"#, 1, 2, 11029, 11029, 2, 1; "L4_ploadrbt_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 ea 00 9f	9f00ea81   	if (!p1) r1 = memb(##0x0) }
	"#, 1, 2, 3, 4, 2, 1; "L4_ploadrbf_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 f2 00 9f	9f00f281   	if (p1.new) r1 = memb(##0x0) }
	"#, 1, 2, 11029, 11029, 1, 1; "L4_ploadrbtnew_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 fa 00 9f	9f00fa81   	if (!p1.new) r1 = memb(##0x0) }
	"#, 1, 2, 3, 4, 1, 1; "L4_ploadrbfnew_abs"
)]
#[test_case(
	r#"
0:	01 cf 00 49	4900cf01 { 	r1 = memb(gp+#0x78) }
	"#, 1, 2, 3, 4, 1, 1; "L2_loadrbgp"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 cf 40 41	4140cf81 { 	if (p1) r1 = memh(r0+#0x78) }
	"#, 1, 2, 11029, 11029, 2, 2; "L2_ploadrht_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	c1 e3 42 9b	9b42e3c1 { 	if (p1) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 2, 2; "L2_ploadrht_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 cf 40 45	4540cf81 { 	if (!p1) r1 = memh(r0+#0x78) }
	"#, 1, 2, 3, 4, 2, 2; "L2_ploadrhf_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	c1 eb 42 9b	9b42ebc1 { 	if (!p1) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 3, 4, 2, 2; "L2_ploadrhf_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 cf 40 43	4340cf81   	if (p1.new) r1 = memh(r0+#0x78) }
	"#, 1, 2, 11029, 11029, 1, 2; "L2_ploadrhtnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 cf 40 47	4740cf81   	if (!p1.new) r1 = memh(r0+#0x78) }
	"#, 1, 2, 3, 4, 1, 2; "L2_ploadrhfnew_io"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 40 30	3040c381 { 	if (p0) r1 = memh(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 2, 2; "L4_ploadrht_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	81 c3 40 31	3140c381 { 	if (!p0) r1 = memh(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 2, 2; "L4_ploadrhf_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 40 32	3240c381   	if (p0.new) r1 = memh(r0+r3<<#0x1) }
	"#, 99, 99, 3, 4, 1, 2; "L4_ploadrhtnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	81 c3 40 33	3340c381   	if (!p0.new) r1 = memh(r0+r3<<#0x1) }
	"#, 1, 2, 3, 4, 1, 2; "L4_ploadrhfnew_rr"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	c1 f3 42 9b	9b42f3c1   	if (p1.new) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 11029, 11029, 1, 2; "L2_ploadrhtnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	c1 fb 42 9b	9b42fbc1   	if (!p1.new) r1 = memh(r2++#-0x4) }
	"#, 1, 2, 3, 4, 1, 2; "L2_ploadrhfnew_pi"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 e2 40 9f	9f40e281   	if (p1) r1 = memh(##0x0) }
	"#, 1, 2, 11029, 11029, 2, 2; "L4_ploadrht_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 d8 17 f2	f217d801   	p1 = cmp.eq(r23,r24) } 
       8:	00 40 00 00	00004000 { 	immext(#0x0)
       c:	81 ea 40 9f	9f40ea81   	if (!p1) r1 = memh(##0x0) }
	"#, 1, 2, 3, 4, 2, 2; "L4_ploadrhf_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 f2 40 9f	9f40f281   	if (p1.new) r1 = memh(##0x0) }
	"#, 1, 2, 11029, 11029, 1, 2; "L4_ploadrhtnew_abs"
)]
#[test_case(
	r#"
0:	00 56 15 f2	f2155600 { 	p0 = cmp.eq(r21,r22)
       4:	01 58 17 f2	f2175801   	p1 = cmp.eq(r23,r24)
       8:	00 40 00 00	00004000   	immext(#0x0)
       c:	81 fa 40 9f	9f40fa81   	if (!p1.new) r1 = memh(##0x0) }
	"#, 1, 2, 3, 4, 1, 2; "L4_ploadrhfnew_abs"
)]
#[test_case(
	r#"
0:	81 c7 40 49	4940c781 { 	r1 = memh(gp+#0x78) }
	"#, 1, 2, 3, 4, 1, 2; "L2_loadrhgp"
)]
fn wrong_sext_loads(
    objdump: &str,
    r21: u32,
    r22: u32,
    r23: u32,
    r24: u32,
    num_packets: u64,
    data_size: u32,
) {
    wrong_size_sext_wrapper(objdump, r21, r22, r23, r24, num_packets, data_size, true)
}

/// These should be sign-extended.
// We want to set the "in" register such that a sign extension occurs
#[test_case(
	r#"
       0:	02 c4 00 80	8000c402 { 	r3:2 = asr(r1:0,#0x4) }
	"#, 0x8000000000000000, HexagonRegister::D1, 0, 0xf800000000000000; "S2_asr_i_p"
)]
#[test_case(
	r#"
       0:	84 c4 00 82	8200c484 { 	r5:4 += asr(r1:0,#0x4) }
	"#, 0x8000000000000000, HexagonRegister::D2, 0, 0xf800000000000000; "S2_asr_i_p_acc"
)]
#[test_case(
	r#"
       0:	04 c4 00 82	8200c404 { 	r5:4 -= asr(r1:0,#0x4) }
	"#, 0x8000000000000000, HexagonRegister::D2, 0xf000000000000000u64, 0xf800000000000000; "S2_asr_i_p_nac"
)]
#[test_case(
	r#"
       0:	04 c4 40 82	8240c404 { 	r5:4 &= asr(r1:0,#0x4) }
	"#, 0x8000000000000000, HexagonRegister::D2, u64::MAX, 0xf800000000000000; "S2_asr_i_p_and"
)]
#[test_case(
	r#"
       0:	84 c4 40 82	8240c484 { 	r5:4 |= asr(r1:0,#0x4) }
	"#, 0x8000000000000000, HexagonRegister::D2, 0, 0xf800000000000000; "S2_asr_i_p_or"
)]
#[test_case(
	r#"
       0:	e2 c4 c0 80	80c0c4e2 { 	r3:2 = asr(r1:0,#0x4):rnd }
	"#, 0x8000000000000010, HexagonRegister::D1, 0, 0xfc00000000000001; "S2_asr_i_p_rnd"
)]
fn arithmetic_shift_right_doubleword(
    objdump: &str,
    in_reg_startval: u64,
    out_reg: HexagonRegister,
    out_reg_startval: u64,
    expected_output: u64,
) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);
    cpu.write_register(HexagonRegister::D0, in_reg_startval)
        .unwrap();
    cpu.write_register(out_reg, out_reg_startval).unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, 1).unwrap();
    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    let out_reg_endval = cpu.read_register::<u64>(out_reg).unwrap();
    assert_eq!(out_reg_endval, expected_output);
}

/// Also asr_r_vh, but not implemented.
/// Also asrhub_rnd_sat, but not implemented
/// Also asrhub_sat, but not implemneted
/// TODO: signed values for the shfits might not work still.
#[test_case(
	r#"
       0:	02 c4 80 80	8080c402 { 	r3:2 = vasrh(r1:0,#0x4) }
	"#, 0x8000800080008000, 0xf800f800f800f800; "S2_asr_i_vh"
)]
#[test_case(
	r#"
       0:	02 c4 20 80	8020c402 { 	r3:2 = vasrh(r1:0,#0x4):raw }
	"#, 0x8010801080108010, 0xfc01fc01fc01fc01; "S5_vasrhrnd"
)]
#[test_case(
	r#"
       0:	02 c4 40 80	8040c402 { 	r3:2 = vasrw(r1:0,#0x4) }
	"#, 0x8000000080000000, 0xf8000000f8000000; "S2_asr_i_vw"
)]
#[test_case(
	r#"
       0:	02 c4 00 c3	c300c402 { 	r3:2 = vasrw(r1:0,r4) }
	"#, 0x8000000080000000, 0xf8000000f8000000; "S2_asr_r_vw"
)]
fn vector_asr_doubleword(objdump: &str, in_reg_val: u64, out_val_expected: u64) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    cpu.write_register(HexagonRegister::D0, in_reg_val).unwrap();
    cpu.write_register(HexagonRegister::R4, 4u32).unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, 1).unwrap();
    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    let out_reg_endval = cpu.read_register::<u64>(HexagonRegister::D1).unwrap();
    assert_eq!(out_reg_endval, out_val_expected);
}

#[test_case(
	r#"
       0:	42 d2 c0 88	88c0d242 { 	r2 = vasrw(r1:0,#0x12) }
	"#, 0x8000000080000000, 0xe000e000; "S2_asr_i_svw_trun"
)]
#[test_case(
	r#"
       0:	42 c4 00 c5	c500c442 { 	r2 = vasrw(r1:0,r4) }
	"#, 0x8000000080000000, 0xe000e000; "S2_asr_r_svw_trun"
)]
fn vector_asr_word(objdump: &str, in_reg_val: u64, out_val_expected: u32) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    cpu.write_register(HexagonRegister::D0, in_reg_val).unwrap();
    cpu.write_register(HexagonRegister::R4, 18u32).unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, 1).unwrap();
    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    let out_reg_endval = cpu.read_register::<u32>(HexagonRegister::R2).unwrap();
    assert_eq!(out_reg_endval, out_val_expected);
}

#[test_case(
	r#"
       0:	01 c4 00 8c	8c00c401 { 	r1 = asr(r0,#0x4) }
	"#, 0x80000000, HexagonRegister::R1, 0, 0xf8000000; "S2_asr_i_r"
)]
#[test_case(
	r#"
       0:	02 c4 40 8e	8e40c402 { 	r2 &= asr(r0,#0x4) }
	"#, 0x80000000, HexagonRegister::R2, u32::MAX, 0xf8000000; "S2_asr_i_r_and"
)]
#[test_case(
	r#"
       0:	82 c4 40 8e	8e40c482 { 	r2 |= asr(r0,#0x4) }
	"#, 0x80000000, HexagonRegister::R2, 0, 0xf8000000; "S2_asr_i_r_or"
)]
#[test_case(
	r#"
       0:	01 c4 40 8c	8c40c401 { 	r1 = asr(r0,#0x4):rnd }
	"#, 0x80000010, HexagonRegister::R1, 0, 0xfc000001; "S2_asr_i_r_rnd"
)]
#[test_case(
	r#"
       0:	82 c4 00 8e	8e00c482 { 	r2 += asr(r0,#0x4) }
	"#, 0x80000000, HexagonRegister::R2, 0, 0xf8000000; "S2_asr_i_r_acc"
)]
#[test_case(
	r#"
       0:	02 c4 00 8e	8e00c402 { 	r2 -= asr(r0,#0x4) }
	"#, 0x80000000, HexagonRegister::R2, 0xf0000000, 0xf8000000; "S2_asr_i_r_nac"
)]
fn arithmetic_shift_right_word(
    objdump: &str,
    in_reg_startval: u32,
    out_reg: HexagonRegister,
    out_reg_startval: u32,
    expected_output: u32,
) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);
    cpu.write_register(HexagonRegister::R0, in_reg_startval)
        .unwrap();
    cpu.write_register(out_reg, out_reg_startval).unwrap();

    let exit = cpu.execute(&mut mmu, &mut ev, 1).unwrap();
    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    let out_reg_endval = cpu.read_register::<u32>(out_reg).unwrap();
    assert_eq!(out_reg_endval, expected_output);
}

// Order of operations test cases require both the operation
// (arithmetic/logical) shift left/right. Then there is an operation,
// which is performed at the wrong time, thereby yielding an unsatisfactory result.

/// The operation enum, describing what operation to do
#[derive(Copy, Clone)]
pub enum OOOperation {
    ArithmeticShiftLeft,
    LogicalShiftLeft,
    ArithmeticShiftRight,
    LogicalShiftRight,
}

/// Post-operation
#[derive(Debug, Copy, Clone)]
pub enum OOPostOperation {
    Add,
    And,
    Or,
    Xor,
    Sub,
    None,
}

#[test_case(
	r#"
       0:	02 c3 80 cc	cc80c302 { 	r2 -= asr(r0,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::Sub; "S2_asr_r_r_nac"
)]
#[test_case(
	r#"
       0:	82 c3 80 cc	cc80c382 { 	r2 -= asl(r0,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Sub; "S2_asl_r_r_nac"
)]
#[test_case(
	r#"
       0:	42 c3 80 cc	cc80c342 { 	r2 -= lsr(r0,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Sub; "S2_lsr_r_r_nac"
)]
#[test_case(
	r#"
       0:	c2 c3 80 cc	cc80c3c2 { 	r2 -= lsl(r0,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Sub; "S2_lsl_r_r_nac"
)]
#[test_case(
	r#"
       0:	02 c3 40 cc	cc40c302 { 	r2 &= asr(r0,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::And; "S2_asr_r_r_and"
)]
#[test_case(
	r#"
       0:	82 c3 40 cc	cc40c382 { 	r2 &= asl(r0,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::And; "S2_asl_r_r_and"
)]
#[test_case(
	r#"
       0:	42 c3 40 cc	cc40c342 { 	r2 &= lsr(r0,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::And; "S2_lsr_r_r_and"
)]
#[test_case(
	r#"
       0:	c2 c3 40 cc	cc40c3c2 { 	r2 &= lsl(r0,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::And; "S2_lsl_r_r_and"
)]
#[test_case(
	r#"
       0:	02 c3 00 cc	cc00c302 { 	r2 |= asr(r0,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::Or; "S2_asr_r_r_or"
)]
#[test_case(
	r#"
       0:	82 c3 00 cc	cc00c382 { 	r2 |= asl(r0,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Or; "S2_asl_r_r_or"
)]
#[test_case(
	r#"
       0:	42 c3 00 cc	cc00c342 { 	r2 |= lsr(r0,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Or; "S2_lsr_r_r_or"
)]
#[test_case(
	r#"
       0:	c2 c3 00 cc	cc00c3c2 { 	r2 |= lsl(r0,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Or; "S2_lsl_r_r_or"
)]
fn order_of_operations_32(objdump: &str, op: OOOperation, post_op: OOPostOperation) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    for i in 1..1000 {
        order_of_operations_helper(&mut cpu, &mut mmu, &mut ev, op, post_op, 4, 0xea43, i, 5);
        order_of_operations_helper(
            &mut cpu,
            &mut mmu,
            &mut ev,
            op,
            post_op,
            4,
            -2i64 as u64,
            i,
            5,
        );
    }
    for i in (u32::MAX - 1000)..u32::MAX {
        order_of_operations_helper(
            &mut cpu, &mut mmu, &mut ev, op, post_op, 4, 0xea43, i as u64, 5,
        );
        order_of_operations_helper(
            &mut cpu,
            &mut mmu,
            &mut ev,
            op,
            post_op,
            4,
            -2i64 as u64,
            i as u64,
            5,
        );
    }
}

#[test_case(
	r#"
       0:	8a c3 cc cb	cbccc38a { 	r11:10 += asl(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Add; "S2_asl_r_p_acc"
)]
#[test_case(
	r#"
       0:	4a c3 cc cb	cbccc34a { 	r11:10 += lsr(r13:12,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Add; "S2_lsr_r_p_acc"
)]
#[test_case(
	r#"
       0:	ca c3 cc cb	cbccc3ca { 	r11:10 += lsl(r13:12,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Add; "S2_lsl_r_p_acc"
)]
#[test_case(
	r#"
       0:	0a c3 8c cb	cb8cc30a { 	r11:10 -= asr(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::Sub; "S2_asr_r_p_nac"
)]
#[test_case(
	r#"
       0:	8a c3 8c cb	cb8cc38a { 	r11:10 -= asl(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Sub; "S2_asl_r_p_nac"
)]
#[test_case(
	r#"
       0:	4a c3 8c cb	cb8cc34a { 	r11:10 -= lsr(r13:12,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Sub; "S2_lsr_r_p_nac"
)]
#[test_case(
	r#"
       0:	ca c3 8c cb	cb8cc3ca { 	r11:10 -= lsl(r13:12,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Sub; "S2_lsl_r_p_nac"
)]
#[test_case(
	r#"
       0:	0a c3 4c cb	cb4cc30a { 	r11:10 &= asr(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::And; "S2_asr_r_p_and"
)]
#[test_case(
	r#"
       0:	8a c3 4c cb	cb4cc38a { 	r11:10 &= asl(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::And; "S2_asl_r_p_and"
)]
#[test_case(
	r#"
       0:	4a c3 4c cb	cb4cc34a { 	r11:10 &= lsr(r13:12,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::And; "S2_lsr_r_p_and"
)]
#[test_case(
	r#"
       0:	ca c3 4c cb	cb4cc3ca { 	r11:10 &= lsl(r13:12,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::And; "S2_lsl_r_p_and"
)]
#[test_case(
	r#"
       0:	0a c3 0c cb	cb0cc30a { 	r11:10 |= asr(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::Or; "S2_asr_r_p_or"
)]
#[test_case(
	r#"
       0:	8a c3 0c cb	cb0cc38a { 	r11:10 |= asl(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Or; "S2_asl_r_p_or"
)]
#[test_case(
	r#"
       0:	4a c3 0c cb	cb0cc34a { 	r11:10 |= lsr(r13:12,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Or; "S2_lsr_r_p_or"
)]
#[test_case(
	r#"
       0:	ca c3 0c cb	cb0cc3ca { 	r11:10 |= lsl(r13:12,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Or; "S2_lsl_r_p_or"
)]
#[test_case(
	r#"
       0:	0a c3 6c cb	cb6cc30a { 	r11:10 ^= asr(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftRight, OOPostOperation::Xor; "S2_asr_r_p_xor"
)]
#[test_case(
	r#"
       0:	8a c3 6c cb	cb6cc38a { 	r11:10 ^= asl(r13:12,r3) }
	"#, OOOperation::ArithmeticShiftLeft, OOPostOperation::Xor; "S2_asl_r_p_xor"
)]
#[test_case(
	r#"
       0:	4a c3 6c cb	cb6cc34a { 	r11:10 ^= lsr(r13:12,r3) }
	"#, OOOperation::LogicalShiftRight, OOPostOperation::Xor; "S2_lsr_r_p_xor"
)]
#[test_case(
	r#"
       0:	ca c3 6c cb	cb6cc3ca { 	r11:10 ^= lsl(r13:12,r3) }
	"#, OOOperation::LogicalShiftLeft, OOPostOperation::Xor; "S2_lsl_r_p_xor"
)]
fn order_of_operations_64(objdump: &str, op: OOOperation, post_op: OOPostOperation) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);

    for i in 1..1000 {
        order_of_operations_helper(&mut cpu, &mut mmu, &mut ev, op, post_op, 8, 0xea43, i, 5);
        order_of_operations_helper(
            &mut cpu,
            &mut mmu,
            &mut ev,
            op,
            post_op,
            8,
            -2i64 as u64,
            i,
            5,
        );
    }
    for i in (u64::MAX - 1000)..u64::MAX {
        order_of_operations_helper(&mut cpu, &mut mmu, &mut ev, op, post_op, 8, 0xea43, i, 5);
        order_of_operations_helper(
            &mut cpu,
            &mut mmu,
            &mut ev,
            op,
            post_op,
            8,
            -2i64 as u64,
            i,
            5,
        );
    }
}

fn order_of_operations_helper(
    cpu: &mut HexagonPcodeBackend,
    mmu: &mut Mmu,
    ev: &mut EventController,
    op: OOOperation,
    post_op: OOPostOperation,
    size: u8,
    dest_start: u64,
    start: u64,
    shift: u32,
) {
    cpu.set_pc(0x1000).unwrap();

    // Overwrite start with a truncated value if 32 bits
    let start = if size == 4 {
        cpu.write_register(HexagonRegister::R0, start as u32)
            .unwrap();
        cpu.write_register(HexagonRegister::R2, dest_start as u32)
            .unwrap();

        // Sign extend it here
        (start as i64) as u64
    } else if size == 8 {
        cpu.write_register(HexagonRegister::D6, start).unwrap();
        cpu.write_register(HexagonRegister::D5, dest_start).unwrap();

        start
    } else {
        unreachable!()
    };

    // Write the shift, which is 32 bits anyway
    cpu.write_register(HexagonRegister::R3, shift as u32)
        .unwrap();

    let exit = cpu.execute(mmu, ev, 1).unwrap();
    assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

    // Read the result, match with our expectations
    // The only consideration is that
    let shifted = match op {
        // same i
        OOOperation::LogicalShiftLeft | OOOperation::ArithmeticShiftLeft if size == 4 => {
            ((start as u32) << shift) as u64
        }
        OOOperation::LogicalShiftLeft | OOOperation::ArithmeticShiftLeft if size == 8 => {
            start << shift
        }
        OOOperation::ArithmeticShiftRight => ((start as i64) >> shift) as u64,
        OOOperation::LogicalShiftRight => start >> shift,
        _ => unreachable!(),
    };

    let result = match post_op {
        OOPostOperation::Add => shifted.wrapping_add(dest_start),
        OOPostOperation::And => shifted & dest_start,
        OOPostOperation::Or => shifted | dest_start,
        OOPostOperation::Xor => shifted ^ dest_start,
        OOPostOperation::Sub => dest_start.wrapping_sub(shifted),
        _ => unreachable!(),
    };

    if size == 4 {
        // Sign extend to 64 bits
        let output = cpu.read_register::<u32>(HexagonRegister::R2).unwrap();

        println!(
            "start {} shift {} shifted is {} {:x} post_op {:?} dest_start {}, output {}",
            start as i32, shift, shifted as i32, shifted as u32, post_op, dest_start, output as u32
        );
        assert_eq!(output, result as u32);
    } else if size == 8 {
        let output = cpu.read_register::<u64>(HexagonRegister::D5).unwrap();

        println!(
            "start {} shift {} shifted is {} {:x} post_op {:?} dest_start {}, output {}",
            start as i64, shift, shifted as i64, shifted, post_op, dest_start, output
        );

        assert_eq!(output, result);
    } else {
        unreachable!()
    };
}

// Multiply instructions that sign extend inappropriately when they should zero-extend.
#[test_case(
	r#"
       0:	0a c3 40 e5	e540c30a { 	r11:10 = mpyu(r0,r3) }
	"#, OOPostOperation::None; "M2_dpmpyuu_s0"
)]
#[test_case(
	r#"
       0:	0a c3 40 e7	e740c30a { 	r11:10 += mpyu(r0,r3) }
	"#, OOPostOperation::Add; "M2_dpmpyuu_acc_s0"
)]
#[test_case(
	r#"
       0:	0a c3 60 e7	e760c30a { 	r11:10 -= mpyu(r0,r3) }
	"#, OOPostOperation::Sub; "M2_dpmpyuu_nac_s0"
)]
fn mpyuu_sext(objdump: &str, post_op: OOPostOperation) {
    let (mut cpu, mut mmu, mut ev) = setup_objdump(objdump);
    let initial_values = [
        0x1u64,
        0x10,
        0x20,
        0x300,
        0xffff,
        0xfea7,
        0xdeadbeef,
        0xffffff87,
        0x78654aff3112,
        0xffffffffffffff89,
    ];
    let mpyu_values = [0xffffff87u32, 6774, 23];

    for initial_value in &initial_values {
        for r0_val in &mpyu_values {
            for r3_val in &mpyu_values {
                cpu.set_pc(0x1000).unwrap();
                cpu.write_register(HexagonRegister::D5, *initial_value)
                    .unwrap();

                cpu.write_register(HexagonRegister::R0, *r0_val).unwrap();
                cpu.write_register(HexagonRegister::R3, *r3_val).unwrap();

                let exit = cpu.execute(&mut mmu, &mut ev, 1).unwrap();
                assert_eq!(exit.exit_reason, TargetExitReason::InstructionCountComplete);

                let mul = (*r0_val as u64).wrapping_mul(*r3_val as u64);
                let out = match post_op {
                    OOPostOperation::Add => mul.wrapping_add(*initial_value),
                    OOPostOperation::Sub => initial_value.wrapping_sub(mul),
                    OOPostOperation::None => mul,
                    _ => unreachable!(),
                };

                let out_emulated = cpu.read_register::<u64>(HexagonRegister::D5).unwrap();

                info!(
                    "initial_value {:x} r0 {:x} r3 {:x} out {}",
                    initial_value, r0_val, r3_val, mul
                );
                assert_eq!(out, out_emulated)
            }
        }
    }
}
