[package]
name = "styx-spi"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
styx-core = { workspace = true }

async-trait = { workspace = true }
async-stream = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
derivative = { workspace = true }
as-any = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }
